---

- include_role:
    name: cpm
  vars:
    - cpm_extract: true
    - cpm_prerequisites: true
    - cpm_install: true
    - cpm_postinstall: true
    - cpm_hardening: true
    - cpm_registration: false
    - cpm_official: false
